### ISSUE TITLE
Create Regional Council Districts Geography

### ISSUE THREAD

**Issue by jdev42092** [NeighborhoodInfoDC/General#12]

**Comment by rpitingolo** [comment]
@ptatian Peter - Jay is close to finishing this process but we have hit a bit of a roadblock.

To create the final weight file, we need block level SF1 data for DC, MD and VA. For 2010, that data is saved on the L drive as:
census_pl_2010_dc
census_pl_2010_md
census_pl_2010_va

However, for 2000, we only have: census_sf1_2010_dc_blks with no corresponding file for the other states.

I found the program that (I think) creates this file (Cen2000_sf1_dc_blks.sas), but it points to a library Cen00sf1 on a D drive that I don't think I can re-create.

Can you please help answer:
1) Do we already have md and vd files processed? Can they be moved to L?
2) If not, do you know where the raw data is so that we can create them?

Thanks.

**Comment by ptatian** [comment]
@rpitingolo Yes, the program you referenced is using SAS data sets that are now in L:\Libraries\Census\Data. But I'm afraid don't have any programs or documentation showing how I created those original data sets. Sorry. 

However, I did find the [Census FTP site for the 2000 SF1 files](https://www2.census.gov/census_2000/datasets/Summary_File_1/), so it would be possible to download and create files for MD and VA. (Perhaps there's a better source for the data, but that's what I could find.) The bad news is you'd have to figure this out from scratch. The good news is we don't need all of the SF1 tables. (I think only P1?) I would just focus on getting the data you need for the task at hand.

Let me know if you have other questions.

**Comment by rpitingolo** [comment]
@ptatian Thanks for checking on this. 

What do you think about me downloading the block-level data from NHGIS and using that for this ? The only variable we need to create the weights is total population, so figuring out how to read-in those raw 2000 SF1 files would be a lot more work for probably not much more benefit. But if you think we will need 2000 SF1 data for MD and VA at some point in the future I can work on building it out from scratch. 

cc: @jdev42092

**Comment by rpitingolo** [comment]
@ptatian @jdev42092 I saved a copy of the data here if you want to take a look before responding: 
L:\Libraries\Census\Raw\NHGIS

**Comment by ptatian** [comment]
I think that's fine. We haven't had any need for those data at all up until now (we don't even use them much for DC) so it doesn't seem worth the extra effort to deal with the Census files.

**Comment by rpitingolo** [comment]
@patian thanks. I'll open a new issue in the census repo for this. @jdev42092 standby for the new file.

**Comment by rpitingolo** [comment]
@jdev42092 in the Census library there is now a dataset called cen2000_nhgis_blks_dc_md_va_wv.sas7bdat

Please use this to create the 2000 weights. You may need to subset the file by state first (you can use the STATEA variable) and then obviously change the name of the population variable in the Macro. Please let me know if you have any questions.
