### ISSUE TITLE
Add code to wt files for dc, va, md

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/General#17]
Added a data step to combine census pl files before running weight programs.

**Comment by jdev42092** [comment]
@rpitingolo Hi Rob, I was just looking back at where things stood for the Regional Council District/ County geographies. This issue is still open, but the branch has been merged and the programs have been run (successfully, I think) on the L:/ drive. Can we close this? And can we move onto the county creation sequence (after making sure this was created correctly)?

**Comment by ptatian** [comment]
Code was merged. Closing issue.
