### ISSUE TITLE
%Finalize_data_set incorrectly used in %Create_summary_from_tracts

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/General#56]
Hi @ptatian ,

@maggiesu0725 got an error when trying to run the %Create_all_summary_from_tracts macro and we traced in back to %Create_summary_from_tracts. It looks like %Finalize_data_set is improperly hard coded to save to the NCDB library. I'm not sure %Finalize_data_set is needed at all in this macro? In which case can it be deleted? Would appreciate if you could take a look. 

`    %Finalize_data_set(
    data=&data_pre.&geosuf,
    out=&data_pre.&geosuf,
    outlib=NCDB,
    label="NCDB summary, DC, &geodlbl",
    sortby=&geo,
    /** Metadata parameters **/
    revisions=%str(&revisions),
    /** File info parameters **/
    printobs=0,
    freqvars=&geo
  )`

**Comment by rpitingolo** [comment]
@ptatian in case you didn't get a notification since I didn't properly tag you the first time. @maggiesu0725

**Comment by ptatian** [comment]
@rpitingolo @maggiesu0725 _%Create_summary_from_tracts()_ is designed so that it can finalize data directly, which is I believe how it is used in NCDB and elsewhere. Yes, I agree that it's a mistake to have the NCDB library and data set label hard coded this way. (Might have been because the macro was originally written for NCDB.) Instead, it should take the _outlib=_ and _data_label=_ parameters that are passed to it. But, there's also a currently unused _register=_ parameter that could control whether the file is finalized or not. 

So, my recommendation would be to keep the _%Finalize_data_set()_ but replace the library and label hard coding and use _register=_ with a _%if...%end_ to control whether the macro gets submitted.

Let me know if that makes sense.

**Comment by rpitingolo** [comment]
@ptatian thanks. This is working properly now. @maggiesu0725
